### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by user334411** [x13a/Duress#1]
Could use some instructions on this one. Perhaps I understood it all wrong but I believe what this app is for is to wipe phone with a duress password using for example wasted. 

I have filled In the following:

Action: me.lucky.wasted.action.TRIGGER
Receiver : me.lucky.wasted/.CodeReceiver
Authentication code: the code in wasted , have tried both with and without code before and the "" characters
Password length: not sure what to put here, have tried many different numbers and then entered that amount of characters on the lock screen 

(Wasted is activated with all permissions )

Perhaps I got it all wrong and this is not how you should do

**Comment by x13a** [comment]
Change receiver to: `me.lucky.wasted/CodeReceiver`, there is no `.` after `/`. I suppose that `me.lucky.wasted` will work too as a receiver.

**For now it is matching by password length, not by password itself.**
It is generic, to use it with Wasted you have to set:

* action to: me.lucky.wasted.action.TRIGGER
* receiver to: me.lucky.wasted/CodeReceiver
* authentication code to the code from Wasted
* password length to your actual password len plus at least two!

Do not forget to activate `Broadcast` trigger in Wasted.
It will trigger on any password with the length you set. If your actual password is 4, than you set Duress to 6. When you write any 6 chars password it will trigger.

**Comment by user334411** [comment]
Working now thanks, both in android and grapheneOS

**Comment by x13a** [comment]
Good to know it, thanks)

**Comment by Beach77** [comment]
> Change the `Receiver` to: `me.lucky.wasted/CodeReceiver`, there is no `.` after `/`. I suppose that `me.lucky.wasted` will work too as a receiver. 

Just to let you know the fdroid guide has `.` after `/` which is some are having problems getting it to work. I came to github to figure out what the problem was and now works after removing the `.`. 

From fdroid: 
>* action: "me.lucky.wasted.action.TRIGGER"
* receiver: "me.lucky.wasted/.TriggerReceiver"
* authentication code: the code from Wasted
* password length: your actual password len plus at least two!

**Comment by x13a** [comment]
> I came to github to figure out what the problem was and now works after removing the .

In the recent version you can use a `.`, it will be removed on set.

```kotlin
setClassName(
    packageName,
    "$packageName.${cls[1].trimStart('.')}",
)
```

**Comment by sourcevault** [comment]
Hi, could you add a small tutorial on how to send a simple message that can be read in logcat like "wipe123" so that I can use this app alongside tasker.
