### ISSUE TITLE
Tutorial or documentation

### ISSUE THREAD

**Issue by Cypher1** [x13a/Duress#10]
It'd be great to have more info on how to make this work.

Currently I haven't been able to see a broadcast message come out of this app and don't want to test with wiping my device.

Also, the readme has 'Wasted' in it and an example config, but it's not clear what the config is expected to do.

Looking forward to using it though. Cheers

**Comment by x13a** [comment]
Install Wasted, check `Broadcast` trigger and turn it on. Do not check `Wipe data`! Use an example config with a secret code you will see in Wasted. After entering PIN/password on the lockscreen with a length you set in Duress settings, Wasted will receive a broadcast message and lock your device. Fingerprint will be disabled and you will have to enter PIN/password.

**Comment by x13a** [comment]
Have added test mode to the recent version

**Comment by Cypher1** [comment]
Thanks!

**Comment by x13a** [comment]
Closing on inactivity
