### ISSUE TITLE
Request: Exact pwd

### ISSUE THREAD

**Issue by InvisibleMan101** [x13a/Duress#12]
Hi,
Love the recent updates but just wanted to know since you can change the secret code and the device listens for that before wiping if it senses that word if you can now possibly add a duress password wipe whereby if it senses on the lockscreen a certain combinations of words or numbers are entered that it triggers the device to wipe?

At the moment with Duress it just senses a limit of characters for this but if you could actually implement a proper duress password wipe it would be amazing! 

Thank you again

**Comment by x13a** [comment]
Done in the recent version
