### ISSUE TITLE
Unusual amount of internet traffic

### ISSUE THREAD

**Issue by DonPicciotto** [x13a/Duress#14]
Hi, sorry to bother you with this, but I can't understand why the app seems to use internet so much. As you can see from the images below the app downloaded and uploaded a lot of data, but I can't find any reason why. The first image is from settings page (I disabled data permission after I saw the amount of data exchanged), the second is from an app called "App Manager". I use Lineage 18.1 (Android 11) with magisk.
Thanks in advance for any answer and for your work.
![Screenshot_20220811-144523_Impostazioni](https://user-images.githubusercontent.com/24780818/184140819-2c39dafe-56ee-4324-ac48-d995aa269922.png)
![Screenshot_20220811-151126_App_Manager_1](https://user-images.githubusercontent.com/24780818/184141407-73ec951a-2020-4e5b-bf45-95e39b02d5e3.png)

**Comment by x13a** [comment]
Hi,

The app does not use internet at all. It does not have Internet permission
for this.

**Comment by DonPicciotto** [comment]
Uhm... then what could have happened? I'm really sorry if I'm bothering you too much, but at this point I'm a little worried

**Comment by x13a** [comment]
First of all check that the app does not have Internet permission. For
example it can be done with Permission Pilot. If all is OK, than I think a
statistic is broken.

**Comment by DonPicciotto** [comment]
Thanks for the answer, I will check deeply

11 ago 2022, 16:52 da ***@***.***:

>
>
>
> First of all check that the app does not have Internet permission. For
>  example it can be done with Permission Pilot. If all is OK, than I think a
>  statistic is broken.
>

**Comment by x13a** [comment]
Closing on inactivity
