### ISSUE TITLE
Add an option to make Duress delete itself on trigger

### ISSUE THREAD

**Issue by eoyst4** [x13a/Duress#16]
When paired with Wasted installed in Shelter (assuming https://github.com/x13a/Wasted/issues/37 gets solved, that is), Duress is meant to be installed in a personal profile, as opposed to the work one, and so it doesn't get deleted by Wasted. I guess I can somehow explain having Shelter on my phone to the police (I needed it for work but never bothered to properly set it up), but not having an app that is literally used to wipe data on your phone. Is it possible to make Duress delete itself when triggered?

**Comment by x13a** [comment]
I suppose it can not be done.

**Comment by eoyst4** [comment]
Whatever then, I guess I'll just give the app and pray nothing bad comes out of it.
