### ISSUE TITLE
howto 

### ISSUE THREAD

**Issue by xyz-nobody** [x13a/Duress#2]
thank you for this application but I don't understand how to make it work with Wasted.

Could you write a little howto in the readme please?

Can you put the application on f-droid?

**Comment by x13a** [comment]
> Could you write a little howto in the readme please?

https://github.com/x13a/Duress/issues/1#issuecomment-1049458803

> Can you put the application on f-droid?

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10651

**Comment by x13a** [comment]
Closing on inactivity
