### ISSUE TITLE
Didn't work in Android 13

### ISSUE THREAD

**Issue by zyh941** [x13a/Duress#20]
Hello, I am a new user of duress app. I have checked previous issues, but here I am not sure if my configuration sets correctly. The duress test works, but when I try to enter a 6 PIN on the lock screen, I can still unlock my phone with fingerprint and there is no broadcast of duress or wasted and the wrong password cannot trigger forced PIN unlocking method. I used this method to check in my Android 9 phone, same problem. The screenshots of my configuration shows below: Please help me...
Device: Pixel 5, running stock Android 13
App version: Duress 1.0.9, Wasted 1.5.9
Duress Accessibility enabled, Wasted Device admin enabled. My regular PIN is 4 digit.
<img width="540" alt="Screenshot_20220829-185838" src="https://user-images.githubusercontent.com/95530307/187189422-1cd77a54-0bed-4b77-9cf6-5ffedc8cb9cb.png">
<img width="540" alt="Screenshot_20220829-190057" src="https://user-images.githubusercontent.com/95530307/187189463-59e700db-71b6-4e4a-ba2d-1125f4ba6fa1.png">
![Screenshot_20220829-190106](https://user-images.githubusercontent.com/95530307/187189491-f5c85dbc-a44a-433b-8125-09b57a0a0ec4.png)

**Comment by x13a** [comment]
Hello,

Change _receiver_ to `me.lucky.wasted/.TriggerReceiver`, the _key_ has to `code`, the _value_ has to be your secret.
