### ISSUE TITLE
Feature Request: Use Fingerprint on Lockscreen

### ISSUE THREAD

**Issue by Beachboy99** [x13a/Duress#21]
For the case someone want to force me to unlock my Device via Fingerprint, I would love to be able to wipe it by using just another Finger than the one i to unlock normally.
E.g.:
Lets say i use the Indexfinger to unlock to usw the device normal. 
I would use the Middlefinger to wipe the device (when locked) .
Is this possible ?

**Comment by x13a** [comment]
It can not be done.

**Comment by Beachboy99** [comment]
Thank you for looking into this and the reply.

And thank you for Duress, its awesome!
